### ISSUE TITLE
vite not serving

### ISSUE THREAD

**Issue by akkayy** [richardeschloss/nuxt-vite#5]
Thanks for this repo. I followed the instructions to the word. While the nuxt dev opens just fine, vite dev throws an error for me as below. Kindly advise if I have to install any additional dependencies. I'm on mac osx catalina v10.15.3. Thanks you! 

![image](https://user-images.githubusercontent.com/73772701/106888965-6d55c100-673b-11eb-89ba-ac572b806992.png)

**Comment by richardeschloss** [comment]
Hi @akkayy , did you solve this by installing [@vitejs/plugin-vue](https://www.npmjs.com/package/@vitejs/plugin-vue) ?

**Comment by richardeschloss** [comment]
While this issue is closed, there are major changes between vite 2.x and vite 1.x. Viewers are encouraged to read the [Vite docs](https://vitejs.dev/) and to consider this thread on [nuxt/vite](https://github.com/nuxt/nuxt.js/issues/7362#issuecomment-787519951) as well as the more mature [nuxt/vite project](https://github.com/nuxt/vite)
